# Generated by Django 2.2 on 2021-05-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_remove_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
